### ISSUE TITLE
Use Github pages

### ISSUE THREAD

**Issue by psophis** [RxSwiftCommunity/rxswiftcommunity.github.io#1]
This is here for further discussion related using Github pages.

**Comment by ashfurrow** [comment]
I'm really comfortable with middleman, which is what @chriseidhof is using for https://github.com/chriseidhof/ios-videos , and is what I use for https://github.com/ashfurrow/blog and https://github.com/NotificationCenter/notificationcenter.tv . I'm totally open to others, but I have  slight aversion of Jekyll.

I'm 💯 on board with using GitHub pages 👍

**Comment by esttorhe** [comment]
I've never used `middleman` before; just looked at it and seems promising.

I have no preference over what we used except that I have used `Jekyll`/`Octopress` and I'm not a fan :stuck_out_tongue:

**Comment by esttorhe** [comment]
As per RxSwiftCommunity/contributors#5; more precisely here https://github.com/RxSwiftCommunity/contributors/issues/5#issuecomment-165497372

I added @psophis to the `contributors` list

**Comment by ashfurrow** [comment]
Yeah, agreed. I've renamed the repo appropriate, setup `source` as the default branch, and will set up a basic middleman sit (`middleman generate`). Then we can work off of PRs.

I'm not a design dictator, but I'd like to submit for consideration Ash Furrow's fool-proof, three-step plan to making neat websites:

1. Find a neat Bootstrap theme. This looks legit: http://startbootstrap.com/template-overviews/modern-business/
2. Find a cool colour theme. I say we just use the #E61B8F/#90278D gradient, white, and a mid-grey.
3. Put the data in a yaml file.

90% of the time, it works every time.

**Comment by psophis** [comment]
👍

I think we need to discuss the scope of the content before we decide on a theme.

**Comment by bontoJR** [comment]
I will then point community.rxswift.org to it :)

**Comment by psophis** [comment]
As of now its not much more than just a list of projects and a description of our goals.

**Comment by ashfurrow** [comment]
I guess I didn't specify, but the theme I linked to ([preview](http://ironsummitmedia.github.io/startbootstrap-modern-business/)) has some pretty sweet looking tikes that would be _perfect_:

<img width="1187" alt="screen shot 2015-12-17 at 5 25 41 pm" src="https://cloud.githubusercontent.com/assets/498212/11883793/4f832bc4-a4e3-11e5-89eb-668949cb8c22.png">

A title, a short description, and maybe a "Source" button to link to their GitHub page.

**Comment by esttorhe** [comment]
I like the theme; minimal but concise; will let us «showcase» each project and even «feature» some.

I think sticking to the `RxSwift` colors makes perfect sense as well

**Comment by esttorhe** [comment]
Also :100: to what @bontoJR said :smile:

**Comment by ashfurrow** [comment]
OK cool. I'll keep setting some basics up (automated deploys so contributing is easier). @psophis is going to add the projects to the Readme in the mean time so we'll have them ready to go.

**Comment by esttorhe** [comment]
Once we have the «`TODO`» I'll try to pick projects and add them to the site

**Comment by psophis** [comment]
Projects list TODO's in #2

**Comment by ashfurrow** [comment]
What sort of information do we need? A title, description, link? Anything else?

**Comment by psophis** [comment]
See #4 for information needed for each project.

**Comment by ashfurrow** [comment]
Does anyone have a vector version of the RxSwiftCommunity avatar? @orta or @bontoJR ?
