### ISSUE TITLE
Examples section?

### ISSUE THREAD

**Issue by esttorhe** [RxSwiftCommunity/rxswiftcommunity.github.io#14]
I was going to open a `PR` with this one https://github.com/carlosypunto/ReallySimpleMVVMLoginExampleWithRxSwift but doesn't feel like it should be on «apps using `RxSwift`.

Should we have another section for «Examples/Tutorials» or just put it on apps?

**Comment by psophis** [comment]
My idea for the apps section was complete apps that aren't just basic functionality implemented. By that measure ReactiveWeatherExample might not even fit though.

 Don't most projects have an example anyway? Would we link all Demo/Example projects?

**Comment by psophis** [comment]
Maybe we do add a new section for example apps and move ReactiveWeatherExample into it. I'd be ok with that.

**Comment by esttorhe** [comment]
I don't have a strong opinion; hence me asking :smile: 

You are the driving force of this initiative so you should outline what was your vision of this and we can explore the path towards there

**Comment by psophis** [comment]
Lets put it in apps for now. If we have more apps in the future we can categorize them then.

**Comment by esttorhe** [comment]
Got it. Closing this
