### ISSUE TITLE
Add repos from original issue

### ISSUE THREAD

**Issue by ashfurrow** [RxSwiftCommunity/rxswiftcommunity.github.io#2]
This is more of a "todo" once we have it figured out where/what this repo will be.

https://github.com/RxSwiftCommunity/contributors/issues/5

**Comment by psophis** [comment]
I have this in a README.md format similar to awesome-swift as of now. Should I make a PR for that or wait until middleman is setup?

**Comment by ashfurrow** [comment]
That's a great idea!

**Comment by psophis** [comment]
Think about this again. I'll just list them here. Now the section are best fit, but could use some massaging.

## Demo Applications
Applications that demonstrate good and extensive use of RxSwift.

* [Eidolon](https://github.com/artsy/eidolon)
* [ReactiveWeatherExample](https://github.com/marinbenc/ReactiveWeatherExample)

## Projects

### RxSwift Abstractions
Abstracts RxSwift or some idea with RxSwift in some way.

* [Action](https://github.com/RxSwiftCommunity/Action)
* [RxEasing](https://github.com/lintmachine/RxEasing)

### Projects that Extend Other Projects with RxSwift
Adds RxSwift extension to another project or API. Could be a simple
gist as well.

* [Moya-ObjectMapper](https://github.com/ivanbruel/Moya-ObjectMapper)
* [NSObject-Rx](https://github.com/RxSwiftCommunity/NSObject-Rx)
* [Parse-RxSwift](https://github.com/bluelinelabs/Parse-RxSwift)
* [RxAlamofire](https://github.com/RxSwiftCommunity/RxAlamofire)
* [RxViewModel](https://github.com/RxSwiftCommunity/RxViewModel)

### Projects with RxSwift Extensions
Optional use of RxSwift as part of the project.

* [Moya](https://github.com/Moya/Moya)

**Comment by psophis** [comment]
This list might be be better as separate issues.
