### ISSUE TITLE
Weird column issue

### ISSUE THREAD

**Issue by ashfurrow** [RxSwiftCommunity/rxswiftcommunity.github.io#37]
![screen shot 2016-04-27 at 9 27 22 am](https://cloud.githubusercontent.com/assets/498212/14853621/477bce2a-0c5a-11e6-923b-0be219bc9702.png)

**Comment by tomcreighton** [comment]
Depending on how "fix this for real" vs. "throw jQuery at it" – a distinction I'm not sure makes any sense – you may want to check http://packery.metafizzy.co.

**Comment by ashfurrow** [comment]
I'm always game for throwing stuff at other stuff, but the GPLv3 license scared me off quite a bit 😬 Was not aware the GPL neckbeards contributed to – or were even aware of – jQuery.

**Comment by leopic** [comment]
What about Masonry http://masonry.desandro.com/ ? No deps and it's MIT licensed

**Comment by leopic** [comment]
@ashfurrow if this not urgent, I can take a crack at it

**Comment by ashfurrow** [comment]
@leopic help would be very much appreciated!

**Comment by leopic** [comment]
Ok I'll take this for a spin tonight

**Comment by tomcreighton** [comment]
100% got Packery and Masonry mixed up. Masonry is awesome.
