### ISSUE TITLE
The URL redirects to the RxSwift GitHub repo instead of a page

### ISSUE THREAD

**Issue by DivineDominion** [RxSwiftCommunity/rxswiftcommunity.github.io#44]
http://community.rxswift.com is no longer functional

**Comment by ashfurrow** [comment]
Oh no! Hmm, not sure who would be able to help with that. @bontoJR?

**Comment by ashfurrow** [comment]
I've moved back to our original rxswiftcommunity.github.io – it look like rxswit.org has been retired and has all URLs redirecting to the repo. Sorry this escaped our notice, thanks for opening the issue!
