### ISSUE TITLE
GitHub rate-limiting issue

### ISSUE THREAD

**Issue by freak4pc** [RxSwiftCommunity/rxswiftcommunity.github.io#69]
The GitHub API is unfortunately rate-limiting us even though we're using authentication tokens, which should not be the case.

![b6e45ff6-bcba-4f41-bb67-b95c34e8896e](https://user-images.githubusercontent.com/605076/36985859-65518bca-2066-11e8-9c36-adf008715f90.png)

I've pinged a buddy of mine at GitHub to help with this issue and will report back here with findings.

**Comment by ashfurrow** [comment]
Could be the authentication strategy? Maybe a personal access token would work in lieu of the GitHub app token (which may be different?) I'm not sure.

**Comment by freak4pc** [comment]
Personal access token would be good - I just highly prefer it would be a "RxSwiftCommunity" token and not my own or yours. If GitHub won't have a proper solution for this by tomorrow or the next day I'll for PAT and be done with it for now :)

**Comment by freak4pc** [comment]
Yeah, I'm definitely doing _something_ wrong. I'll dig into this a bit later, but hitting the /rate_limit endpoint with the tokens results in very low limits indeed :) 

```
{
  "resources": {
    "core": {
      "limit": 60,
      "remaining": 52,
      "reset": 1520266715
    },
    "search": {
      "limit": 10,
      "remaining": 10,
      "reset": 1520266758
    },
    "graphql": {
      "limit": 0,
      "remaining": 0,
      "reset": 1520270298
    }
  },
  "rate": {
    "limit": 60,
    "remaining": 52,
    "reset": 1520266715
  }
}
```

**Comment by freak4pc** [comment]
Opted for the easy PAT solution 🤷‍♂️ Closing this :)
